version: 1
formatters:
  myFormatter:
    format: '[%(asctime)s] [%(levelname)s] %(name)s: %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: myFormatter
    stream: ext://sys.stderr
  file:
    class: logging.handlers.RotatingFileHandler
    filename: pidlwick.log
    formatter: myFormatter
    encoding: utf-8
    maxBytes: 33554432  # 32 MiB
    backupCount: 5  # Rotate through 5 files
loggers:
  discord:
    level: INFO
    handlers: [console, file]
    propagate: 0
  app:
    level: DEBUG
    handlers: [console, file]
    propagate: 0
root:
  level: DEBUG
  handlers: [console]
